AWSTemplateFormatVersion: "2010-09-09"
Description: Create an Amazon EC2 instance running the Amazon Linux AMI. The AMI is chosen based
  on the region in which the stack is run. **WARNING** This template creates an Amazon
  EC2 instance. You will be billed for the AWS Resources

Parameters:
    MachineImage:
        Type: AWS::EC2::Image::Id
    InstanceType:
        Type: String
        Default: t2.micro
    KeyName:
        Type: AWS::EC2::KeyPair::KeyName
    SubnetId:
        Type: AWS::EC2::Subnet::Id
    SecurityGroups:
        Type: List<AWS::EC2::SecurityGroup::Id>
    VolumeSize:
        Type: Number
        Default: 8
        Description: Enter the size of the volume
        MaxValue: 10


Resources:
    LinuxEC2:
        Type: AWS::EC2::Instance
        Properties:
            ImageId: !Ref MachineImage
            InstanceType: !Ref InstanceType
            KeyName: !Ref KeyName
            SecurityGroupIds: !Ref SecurityGroups
            SubnetId: !Ref SubnetId
            InstanceInitiatedShutdownBehavior: terminate
            BlockDeviceMappings:
                - DeviceName: "/dev/xvda"
                  Ebs:
                    VolumeSize: !Ref VolumeSize
                - DeviceName: "/dev/sdb"
                  VirtualName : "ephemeral0"

Outputs:
    LinuxEC2:
        Value: !Ref LinuxEC2
    LinuxEC2PrivateIP:
        Value: !GetAtt LinuxEC2.PrivateIp
    LinuxEC2PublicIP:
        Value: !GetAtt LinuxEC2.GetAtt
